// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using Melia.Zone.Scripting;
using static Melia.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_c_fedimian : GeneralScript
{
	protected override void Load()
	{
		AddNpc(3, 147439, "Squire Master", "c_fedimian", 694.0, 291.0, 114.0, 0.0, "JOB_SQUIRE3_1_NPC", "", "", -2, 30.0);
		AddNpc(12, 20041, "", "c_fedimian", -531.0, 163.0, -428.0, 0.0, "", "JOB_FEDIMIAN_TRIGGER", "", -2, 100.0);
		AddNpc(100, 147449, "Grita", "c_fedimian", 127.0, 538.0, 517.0, -56.889999, "FEDIMIAN_GRITA", "", "", -2, 30.0);
		AddNpc(101, 20011, "Supply Soldier", "c_fedimian", -493.0, 179.0, -534.0, 92.68, "FEDIMIAN_DETECTIVE_GUARD", "", "", -2, 30.0);
		AddNpc(104, 20013, "Supply Officer", "c_fedimian", -566.0, 462.0, 168.0, 0.0, "CRIMINAL", "GHOST_APPEAR", "", -2, 30.0);
		AddNpc(105, 20148, "Eulalia", "c_fedimian", -788.0, 451.0, 283.0, -52.790001, "REMAIN39_SQ03_GIRL", "", "", -2, 30.0);
		AddNpc(106, 57238, "Rogue Master", "c_fedimian", 169.0, 426.299988, 162.179993, 0.0, "MASTER_ROGUE", "", "", -2, 40.0);
		AddNpc(108, 151034, "Fedimian Item Merchant", "c_fedimian", -631.320007, 169.309998, -174.899994, -90.0, "FED_TOOL", "", "", -2, 40.0);
		AddNpc(113, 40070, "Bulletin Board", "c_fedimian", 245.720001, 478.359985, 398.100006, -82.0, "FEDIMIAN_SIGN1", "", "", -2, 30.0);
		AddNpc(114, 20165, "City Middle-Aged Man", "c_fedimian", -899.01001, 521.340027, 333.519989, -56.0, "FEDIMIAN_OLDMAN1", "", "", -2, 40.0);
		AddNpc(115, 40070, "Bulletin Board", "c_fedimian", 671.119995, 160.550003, -84.220001, -81.0, "FEDIMIAN_SIGN2", "", "", -2, 40.0);
		AddNpc(116, 40070, "Bulletin Board", "c_fedimian", -879.48999, 447.559998, 87.510002, -70.0, "FEDIMIAN_SIGN3", "", "", -2, 40.0);
		AddNpc(117, 40070, "Bulletin Board", "c_fedimian", 630.710022, 747.099976, 1101.48999, -71.0, "FEDIMIAN_SIGN4", "", "", -2, 40.0);
		AddNpc(118, 20026, "", "c_fedimian", -606.659973, 447.559998, 63.169998, 0.0, "", "JOB_ROGUE5_1", "", -2, 150.0);
		AddNpc(120, 57227, "Druid Master", "c_fedimian", 432.940002, 482.23999, 808.289978, -70.0, "JOB_DRUID3_1_NPC", "", "", -2, 40.0);
		AddNpc(122, 147437, "Armand", "c_fedimian", -658.0, 168.0, -250.0, -21.16, "FEDIMIAN_NPC_11", "", "", -2, 40.0);
		AddNpc(123, 20114, "Marta", "c_fedimian", 11.0, 543.0, 550.0, 0.0, "FEDIMIAN_NPC_12", "", "", -2, 40.0);
		AddNpc(125, 147443, "Doppelsoeldner Master", "c_fedimian", 220.699997, 160.550003, -81.839996, -90.0, "MASTER_DOPPELSOELDNER", "", "", -2, 40.0);
		AddNpc(126, 151036, "Fedimian Blacksmith", "c_fedimian", 120.0, 160.0, -504.0, -15.26, "BLACKSMITH_FEDIMIAN", "", "", -2, 80.0);
		AddNpc(127, 20171, "Market Manager", "c_fedimian", -391.0, 160.0, -266.0, -90.0, "MARKET_FEDIMIAN", "", "", -2, 0.0);
		AddNpc(128, 156027, "Fedimian Storage Keeper", "c_fedimian", -187.0, 160.0, -235.0, -68.629997, "WAREHOUSE_FEDIMIAN", "", "", -2, 0.0);
		AddNpc(131, 151029, "Pile Of Boxes 01", "c_fedimian", -218.0, 160.0, -230.0, -84.919998, "", "", "", -2, 0.0);
		AddNpc(132, 147469, "No Shadow Npc", "c_fedimian", 186.809998, 825.150024, 855.789978, 0.0, "SHINOBI_POTTER", "", "", -2, 40.0);
		AddNpc(132, 147469, "No Shadow Npc", "c_fedimian", -735.820007, 208.220001, -133.690002, 0.0, "SHINOBI_POTTER", "", "", -2, 40.0);
		AddNpc(132, 147469, "No Shadow Npc", "c_fedimian", 354.630005, 482.23999, 826.609985, 9.0, "SHINOBI_POTTER", "", "", -2, 40.0);
		AddNpc(134, 20068, "Tp Trader Leticia", "c_fedimian", 189.88295, 161.387573, -205.793701, -90.0, "TP_NPC", "", "", -2, 60.0);
		AddNpc(150, 157039, "Appraiser", "c_fedimian", -41.0, 160.0, -223.0, 270.0, "FEDIMIAN_APPRAISER", "TUTO_APPRAISE_NPC", "", -2, 100.0);
		AddNpc(1003, 157039, "Appraiser", "c_fedimian", -41.0, 160.0, -223.0, 270.0, "FEDIMIAN_APPRAISER_NPC", "", "", -2, 40.0);
		AddNpc(2002, 153194, "Matador Master", "c_fedimian", 740.292847, 291.828796, 259.636475, -64.0, "MATADOR_MASTER", "", "", -2, 40.0);
		AddNpc(2003, 155168, "Adventurer Anastazija", "c_fedimian", 406.735992, 312.01651, 58.329727, -90.0, "EXPLORER_ANASTAZIJA", "", "", -2, 40.0);
		AddNpc(2005, 40070, "Bulletin Board", "c_fedimian", -133.301163, 365.929108, 58.581329, -85.0, "FEDIMIAN_OFFICIAL_BOARD", "", "", -2, 40.0);
		AddNpc(2006, 153208, "Exorcist Master", "c_fedimian", 89.286102, 478.356995, 356.26593, -74.0, "EXORCIST_MASTER", "", "", -2, 40.0);
		AddNpc(2007, 20118, "Tobias", "c_fedimian", 154.977737, 478.855255, 350.673737, -74.0, "CHAR420_STEP321_NPC", "", "", -2, 40.0);
		AddNpc(2008, 147483, "Liora", "c_fedimian", 154.977737, 478.855255, 350.673737, -74.0, "CHAR420_STEP323_NPC1", "", "", -2, 40.0);
		AddNpc(2009, 161002, "Blacksmith Teliavelis", "c_fedimian", 287.909821, 816.855774, 978.20459, 0.0, "FEDIMIAN_TERIAVELIS", "FEDIMIAN_TERIAVELIS", "", -2, 20.0);
	}
}
