// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using Melia.Zone.Scripting;
using static Melia.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_c_Klaipe : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 20115, "Item Merchant", "c_Klaipe", 510.702911, -1.292879, -349.319366, 0.0, "EMILIA", "", "", -2, 40.0);
		AddNpc(2, 20111, "Equipment Merchant", "c_Klaipe", 394.0, -1.0, -475.0, 0.0, "AKALABETH", "", "", -2, 40.0);
		AddNpc(3, 20104, "Accessory Merchant", "c_Klaipe", 268.707733, -1.343773, -610.940063, 0.0, "ALFONSO", "ADDHELP_NPCSHOP", "", -2, 250.0);
		AddNpc(7, 20158, "Juan", "c_Klaipe", -9.0, 156.0, 131.0, 90.0, "ACT_VILLAGERS", "", "", -2, 40.0);
		AddNpc(13, 20105, "[Blacksmith] Hewg", "c_Klaipe", 600.0, -1.0, -83.0, 90.0, "KLAPEDA_BLACKSMITH", "TUTO_REPAIR_NPC", "", -2, 80.0);
		AddNpc(103, 20028, "Peltasta Master", "c_Klaipe", -225.0, 97.0, -385.0, 90.0, "MASTER_PELTASTA", "", "", -2, 20.0);
		AddNpc(106, 20137, "Cryomancer Master", "c_Klaipe", -205.0, 79.0, -515.0, 90.0, "MASTER_ICEMAGE", "", "", -2, 20.0);
		AddNpc(107, 20041, "", "c_Klaipe", -336.0, 79.0, -548.0, 6.17, "", "MASTER_FIREMAGE_BOX_TRIGGER", "", -2, 20.0);
		AddNpc(111, 20021, "Wizard Master", "c_Klaipe", -100.0, 96.0, -275.0, 0.0, "MASTER_WIZARD", "", "", -2, 20.0);
		AddNpc(112, 147447, "Archer Master", "c_Klaipe", -949.0, 241.0, 308.0, 90.0, "MASTER_ARCHER", "", "", -2, 20.0);
		AddNpc(115, 57228, "Krivis Master", "c_Klaipe", -1108.0, 240.0, 512.0, 90.0, "MASTER_KRIWI", "", "", -2, 20.0);
		AddNpc(117, 57224, "Oracle Master", "c_Klaipe", -1021.29, 248.3324, 61.29675, 135.0, "MASTER_ORACLE", "", "", -2, 40.0);
		AddNpc(118, 153203, "Onmyoji Master", "c_Klaipe", -589.0, 149.0, -161.0, 0.0, "ONMYOJI_MASTER", "", "", -2, 40.0);
		AddNpc(130, 40070, "Bulletin Board", "c_Klaipe", -66.0, -1.0, -752.0, 45.0, "KLAPEDA_SIGN30", "", "", -2, 20.0);
		AddNpc(131, 40070, "Bulletin Board", "c_Klaipe", 195.0, -1.0, -641.0, 45.0, "KLAPEDA_SIGN31", "", "", -2, 20.0);
		AddNpc(132, 40070, "Bulletin Board", "c_Klaipe", 58.0, 79.0, -359.0, 45.0, "KLAPEDA_SIGN32", "", "", -2, 20.0);
		AddNpc(133, 40070, "Bulletin Board", "c_Klaipe", -63.0, 148.0, -108.0, 45.0, "KLAPEDA_SIGN33", "", "", -2, 20.0);
		AddNpc(134, 40070, "Bulletin Board", "c_Klaipe", -165.0, -1.0, -958.0, 45.0, "KLAPEDA_SIGN_WELCOME", "", "", -2, 20.0);
		AddNpc(135, 40070, "Bulletin Board", "c_Klaipe", 744.0, -1.0, 192.0, 45.0, "KLAPEDA_SIGN35", "", "", -2, 20.0);
		AddNpc(136, 40070, "Bulletin Board", "c_Klaipe", -125.0, 148.0, -11.0, 45.0, "KLAPEDA_SIGN36", "", "", -2, 20.0);
		AddNpc(209, 40090, "Bulletin Board", "c_Klaipe", -80.0, 148.0, 387.0, 45.0, "KLAPEDA_SIGN9", "", "", -2, 20.0);
		AddNpc(302, 151037, "Fedimian Mercenary Post Manager", "c_Klaipe", -638.0, 240.0, 1017.0, 0.0, "FEDIMIAN_ROTA_02", "", "", -2, 1.0);
		AddNpc(303, 147484, "Brindle", "c_Klaipe", -609.0, 241.0, 867.0, 0.0, "MISSIONSHOP_NPC_01", "", "", -2, 1.0);
		AddNpc(304, 154054, "Legywn Family'S Vassal1", "c_Klaipe", -457.0, 241.0, 895.0, 270.0, "PARTYQUEST_NPC_01", "", "", -2, 1.0);
		AddNpc(305, 151039, "Fedimian Manager", "c_Klaipe", -542.0, 241.0, 882.0, 0.0, "DROPITEM_REQUEST1_NPC", "", "", -2, 1.0);
		AddNpc(306, 47248, "Cat", "c_Klaipe", -77.60321, 149.070877, -142.183456, 0.0, "KLAPEDA_FISHING_CAT", "KLAPEDA_FISHING_CAT", "", -2, 60.0);
		AddNpc(2001, 20139, "Pablo", "c_Klaipe", -60.0, 79.0, -446.0, 0.0, "KLAPEDA_NPC_14", "", "", -2, 0.0);
		AddNpc(2002, 20056, "[Market Manager] Jura", "c_Klaipe", 254.749313, 79.859558, 225.742767, 90.0, "KLAPEDA_MARKET", "TUTO_MARKET_NPC", "", -2, 50.0);
		AddNpc(10005, 40070, "Bulletin Board", "c_Klaipe", 617.0, -1.0, 61.0, 45.0, "KLAPEDA_BOARD_01", "", "", -2, 30.0);
		AddNpc(10009, 153005, "[Companion Trader] Christina", "c_Klaipe", 6.0, -1.0, -760.0, 90.0, "PETSHOP_KLAIPE", "", "", -2, 30.0);
		AddNpc(10011, 47521, "Velheider Crystal", "c_Klaipe", -22.0, -1.0, -757.0, 270.0, "PETSHOP_KLAIPE_PET", "", "", -2, 30.0);
		AddNpc(10013, 152005, "Lena", "c_Klaipe", 68.443634, 148.838791, 485.895386, 0.0, "JOURNEY_SHOP", "TUTO_JOURNAL_NPC", "", -2, 120.0);
		AddNpc(10014, 152004, "Henrika", "c_Klaipe", -292.0, 149.0, 291.0, 0.0, "COLLECTION_SHOP", "", "", -2, 40.0);
		AddNpc(10018, 20068, "Leticia", "c_Klaipe", 282.72168, 79.859558, 148.80867, 90.0, "TP_NPC", "TUTO_TPSHOP_NPC", "", -2, 60.0);
		AddNpc(10021, 155017, "Baron Allerno", "c_Klaipe", -949.0, 241.0, 365.0, 90.0, "LOWLV_BOASTER_MUENCHHAUSEN", "", "", -2, 40.0);
		AddNpc(10023, 150004, "Fishing Spot", "c_Klaipe", -827.234924, 217.910461, 729.855286, 0.0, "", "", "", -2, 220.0);
		AddNpc(10023, 150004, "Fishing Spot", "c_Klaipe", -162.75032, 240.726822, 974.887939, 0.0, "", "", "", -2, 220.0);
		AddNpc(10024, 150008, "Fishing Spot Notice Board", "c_Klaipe", -645.0, 241.0, 694.0, 45.0, "KLAPEDA_FISHING_BOARD", "", "", -2, 40.0);
		AddNpc(10026, 150004, "Fishing Spot", "c_Klaipe", -1032.822388, 217.910461, 436.123688, 0.0, "", "", "", -2, 170.0);
		AddNpc(10026, 150004, "Fishing Spot", "c_Klaipe", -1019.782227, 248.232391, 101.671753, 0.0, "", "", "", -2, 170.0);
		AddNpc(10026, 150004, "Fishing Spot", "c_Klaipe", -554.467346, 217.910461, 975.000916, 0.0, "", "", "", -2, 170.0);
		AddNpc(10027, 158000, "Team Battle League", "c_Klaipe", -389.748047, 241.052032, 605.104187, 0.0, "WORLDPVP_START", "", "", -2, 60.0);
		AddNpc(10061, 147410, "Female Guard", "c_Klaipe", -321.113464, 241.052032, 896.6875, 0.0, "INSTANCE_DUNGEON", "", "", -2, 40.0);
		AddNpc(50001, 40096, "Event Notice Board", "c_Klaipe", 94.879028, 148.82733, 390.55286, 270.0, "STEAM_TREASURE_EVENT", "", "", -2, 40.0);
	}
}
