// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using Melia.Zone.Scripting;
using static Melia.Zone.Scripting.Shortcuts;

public class ProjectEpicNpc_c_orsha : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 40070, "Bulletin Board", "c_orsha", -1077.48999, 500.609985, 332.73999, -62.0, "ORSHA_KEDORLA_BOARD01", "", "", -2, 40.0);
		AddNpc(2, 20066, "Blacksmith Ilanai", "c_orsha", -133.440002, 175.979996, -285.690002, -17.0, "ORSHA_BLACKSMITH", "TUTO_REPAIR_NPC", "", -2, 80.0);
		AddNpc(4, 20063, "Orsha Soldier Male1", "c_orsha", 384.970001, 175.850006, 231.720001, -150.0, "ORSHA_KEDORLA_MEMBER01", "", "", -2, 40.0);
		AddNpc(5, 20065, "Inesa Hamondale", "c_orsha", 86.989998, 176.270004, 713.25, -80.0, "C_ORSHA_HAMONDAIL", "", "", -2, 40.0);
		AddNpc(6, 20059, "Orsha Soldier Female", "c_orsha", 40.709999, 176.270004, 713.97998, -76.0, "C_ORSHA_SOLDIER_01", "", "", -2, 40.0);
		AddNpc(7, 20060, "Orsha Soldier Male", "c_orsha", 140.979996, 176.279999, 712.849976, -110.0, "C_ORSHA_SOLDIER_02", "", "", -2, 40.0);
		AddNpc(8, 154057, "Urbonas", "c_orsha", 895.179993, 176.369995, 702.909973, -90.0, "C_ORSHA_URBONAS", "", "", -2, 40.0);
		AddNpc(9, 20055, "Orsha Item Merchant Alf", "c_orsha", 231.0, 175.0, 166.0, 30.0, "ORSHA_TOOL_NPC", "", "", -2, 40.0);
		AddNpc(10, 40032, "Treasure Chest", "c_orsha", 0.0, 176.0, 150.0, 0.0, "", "", "", -2, 40.0);
		AddNpc(11, 20057, "Accessory Merchant Jurus", "c_orsha", 462.191742, 175.921432, -29.935261, -101.0, "ORSHA_ACCESSARY_NPC", "ORSHA_HQ1_CONDITION", "", -2, 60.0);
		AddNpc(100, 155062, "Swordsman Submaster", "c_orsha", 236.570007, 176.410004, 648.599976, -89.0, "JOB_2_SWORDMAN_NPC", "", "", -2, 40.0);
		AddNpc(101, 155063, "Peltasta Submaster", "c_orsha", -853.0, 500.0, -62.0, 10.0, "JOB_2_PELTASTA_NPC", "", "", -2, 40.0);
		AddNpc(102, 147325, "Hoplite Master", "c_orsha", -1070.180054, 500.609985, 229.960007, -2.0, "JOB_2_HOPLITE_NPC", "", "", -2, 40.0);
		AddNpc(103, 155083, "Cleric Submaster", "c_orsha", -269.959991, 175.979996, -378.040009, -10.0, "JOB_2_CLERIC_NPC", "", "", -2, 40.0);
		AddNpc(104, 155084, "Krivis Submaster", "c_orsha", -612.210022, 368.420013, 608.859985, -16.0, "JOB_2_KRIVIS_NPC", "", "", -2, 40.0);
		AddNpc(105, 155085, "Priest Submaster", "c_orsha", 723.440002, 176.380005, 642.359985, -75.0, "JOB_2_PRIEST_NPC", "", "", -2, 40.0);
		AddNpc(106, 155086, "Bokor Submaster", "c_orsha", 462.399994, 176.399994, 608.869995, -90.0, "JOB_2_BOKOR_NPC", "", "", -2, 40.0);
		AddNpc(107, 57235, "Rodelero Master", "c_orsha", -451.0, 279.0, 419.0, -65.0, "JOB_2_RODELERO_NPC", "", "", -2, 40.0);
		AddNpc(108, 147327, "Cataphract Master", "c_orsha", 934.650024, 73.980003, 146.949997, -19.0, "JOB_2_CATAPHRACT_NPC", "", "", -2, 40.0);
		AddNpc(109, 57226, "Sadhu Master", "c_orsha", 1130.380005, 21.82, 361.980011, 3.0, "JOB_2_SADHU_NPC", "", "", -2, 40.0);
		AddNpc(110, 155088, "Paladin Submaster", "c_orsha", 942.27002, 73.980003, 475.769989, 5.0, "JOB_2_PALADIN_NPC", "", "", -2, 40.0);
		AddNpc(111, 47242, "Torch", "c_orsha", -603.109985, 368.119995, 641.369995, -12.0, "", "", "", -2, 40.0);
		AddNpc(112, 155044, "Monk3", "c_orsha", 915.73999, 176.360001, 708.51001, -69.0, "C_ORSHA_PRANAS", "", "", -2, 40.0);
		AddNpc(116, 155069, "Wizard Submaster", "c_orsha", -274.290009, 177.5, -758.48999, 0.0, "JOB_2_WIZARD_MASTER", "", "", -2, 40.0);
		AddNpc(117, 155070, "Pyromancer Submaster", "c_orsha", -198.660004, 177.429993, -899.400024, 0.0, "JOB_2_PYROMANCER_MASTER", "", "", -2, 40.0);
		AddNpc(118, 155071, "Cryomancer Submaster", "c_orsha", 1035.619995, 73.980003, 79.040001, -90.0, "JOB_2_CRYOMANCER_MASTER", "", "", -2, 40.0);
		AddNpc(119, 147328, "Psychokino Master", "c_orsha", -859.849976, 500.609985, 586.159973, -90.0, "JOB_2_PSYCHOKINO_MASTER", "", "", -2, 40.0);
		AddNpc(120, 57230, "Linker Master", "c_orsha", 609.440002, 148.110001, 341.200012, 0.0, "JOB_2_LINKER_MASTER", "", "", -2, 40.0);
		AddNpc(121, 155074, "Thaumaturge Submaster", "c_orsha", 235.470001, 176.679993, -827.299988, -90.0, "JOB_2_THAUMATURGE_MASTER", "", "", -2, 40.0);
		AddNpc(122, 147442, "Elementalist Master", "c_orsha", -647.75, 317.799988, 289.480011, -45.0, "JOB_2_ELEMENTALIST_MASTER", "", "", -2, 40.0);
		AddNpc(123, 155076, "Archer Submaster", "c_orsha", -182.949997, 176.240005, 658.059998, -90.0, "JOB_2_ARCHER_MASTER", "", "", -2, 40.0);
		AddNpc(124, 155077, "Ranger Submaster", "c_orsha", 691.070007, 177.470001, -197.580002, 0.0, "JOB_2_RANGER_MASTER", "", "", -2, 40.0);
		AddNpc(125, 155078, "Quarrel Shooter Submaster", "c_orsha", 584.309998, 175.850006, 138.139999, -45.0, "JOB_2_QUARRELSHOOTER_MASTER", "", "", -2, 40.0);
		AddNpc(126, 155079, "Sapper Submaster", "c_orsha", 50.122803, 175.983734, -332.239288, 0.0, "JOB_2_SAPPER_MASTER", "", "", -2, 40.0);
		AddNpc(127, 155080, "Hunter Submaster", "c_orsha", -1098.890015, 177.960007, -648.369995, 0.0, "JOB_2_HUNTER_MASTER", "", "", -2, 40.0);
		AddNpc(128, 57233, "Wugushi Master", "c_orsha", -89.379997, 177.220001, -755.539978, -90.0, "JOB_2_WUGUSHI_MASTER", "", "", -2, 40.0);
		AddNpc(129, 155082, "Scout Submaster", "c_orsha", -967.440002, 177.669998, -562.900024, -90.0, "JOB_2_SCOUT_MASTER", "", "", -2, 40.0);
		AddNpc(130, 20058, "Companion Trader Toras", "c_orsha", -109.365021, 176.291122, 362.765045, 14.0, "ORSHA_PETSHOP", "ORSHA_HIDDENQ2_IN_TRIGGER", "", -2, 40.0);
		AddNpc(131, 47521, "Velheider Crystal", "c_orsha", -126.398483, 176.357788, 394.701782, 5.0, "PETSHOP_KLAIPE_PET", "", "", -2, 40.0);
		AddNpc(132, 156008, "Orsha Market Manager", "c_orsha", 213.96463, 175.858093, -12.915084, -86.0, "ORSHA_MARKET", "TUTO_MARKET_NPC", "", -2, 50.0);
		AddNpc(133, 20067, "Storage Keeper Aisa", "c_orsha", 320.216553, 175.885178, 69.167458, 0.0, "ORSHA_WAREHOUSE", "TUTO_STORAGE_NPC", "", -2, 50.0);
		AddNpc(134, 155102, "Florianna", "c_orsha", -985.947144, 500.608337, 415.815247, 0.0, "ORSHA_COLLECTION_SHOP", "", "", -2, 40.0);
		AddNpc(135, 155103, "Rosia", "c_orsha", -451.51416, 324.604187, -89.633614, 0.0, "ORSHA_JOURNEY_SHOP", "TUTO_JOURNAL_NPC", "", -2, 120.0);
		AddNpc(136, 20068, "Tp Trader Leticia", "c_orsha", 47.920361, 175.999512, 36.857758, 0.0, "TP_NPC", "TUTO_TPSHOP_NPC", "", -2, 60.0);
		AddNpc(137, 20062, "Orsha Soldier Female2", "c_orsha", -42.0, 176.0, 207.0, 0.0, "ORSHA_NPC01", "", "", -2, 40.0);
		AddNpc(138, 20064, "Orsha Soldier Male2", "c_orsha", -203.0, 176.0, 537.0, 0.0, "ORSHA_NPC02", "", "", -2, 40.0);
		AddNpc(142, 147466, "Tavern Book", "c_orsha", -143.072723, 175.983734, -203.09024, 22.0, "ORSHA_BOOK01", "", "", -2, 40.0);
		AddNpc(143, 147311, "Book", "c_orsha", -167.755112, 181.373947, -212.696198, 113.0, "", "", "", -2, 40.0);
		AddNpc(149, 151067, "Small Wooden Chest", "c_orsha", -100.209442, 181.647659, -203.313568, 0.0, "ORSHA_BOOK02", "", "", -2, 40.0);
		AddNpc(150, 147392, "Treasure Box 1", "c_orsha", -461.540009, 505.130005, -277.0, -135.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(151, 151128, "Miko Altar", "c_orsha", 113.878227, 176.67984, -1352.280762, 0.0, "HIDDEN_MIKO_JUROTA", "", "", -2, 40.0);
		AddNpc(1004, 40070, "Bulletin Board", "c_orsha", -217.202942, 215.416809, -37.602386, -23.0, "ORSHA_CHAR119_MSTEP1", "", "", -2, 40.0);
		AddNpc(50001, 40096, "Event Notice Board", "c_orsha", -451.22076, 324.60419, -154.9817, 0.0, "STEAM_TREASURE_EVENT", "", "", -2, 40.0);
	}
}
