// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using Melia.Zone.Scripting;
using static Melia.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_c_request_1 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(10, 152002, "Old Man", "c_request_1", 98.0, 0.0, -29.0, 315.0, "FEDIMIAN_BOARD_01", "", "", -2, 1.0);
	}
}
