// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using Melia.Zone.Scripting;
using static Melia.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_out : GeneralScript
{
	protected override void Load()
	{
		AddNpc(151, 46212, "Box", "f_siauliai_out", -1086.0, 42.0, -1522.0, 85.0, "SIAULIAIOUT_119_2", "", "", -2, 50.0);
		AddNpc(152, 46212, "Box", "f_siauliai_out", -1197.0, 42.0, -1627.0, 85.0, "SIAULIAIOUT_119_3", "", "", -2, 50.0);
		AddNpc(153, 46212, "Box", "f_siauliai_out", -1237.0, 90.0, -1457.0, 85.0, "SIAULIAIOUT_119_4", "", "", -2, 50.0);
		AddNpc(154, 46212, "Box", "f_siauliai_out", -1160.0, 171.0, -1225.0, 85.0, "SIAULIAIOUT_119_5", "", "", -2, 50.0);
		AddNpc(155, 46212, "Box", "f_siauliai_out", -1364.0, 171.0, -1002.0, 85.0, "SIAULIAIOUT_119_6", "", "", -2, 50.0);
		AddNpc(156, 46212, "Box", "f_siauliai_out", -1576.48999, 42.830002, -1673.099976, 85.0, "SIAULIAIOUT_119_7", "", "", -2, 50.0);
		AddNpc(157, 46212, "Box", "f_siauliai_out", -1807.0, 43.0, -1853.0, 85.0, "SIAULIAIOUT_119_8", "", "", -2, 50.0);
		AddNpc(158, 46212, "Box", "f_siauliai_out", -2078.320068, 42.830002, -1782.609985, 91.0, "SIAULIAIOUT_119_9", "", "", -2, 50.0);
		AddNpc(159, 152068, "Stone", "f_siauliai_out", -1749.0, 171.0, -1110.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(160, 152068, "Stone", "f_siauliai_out", -1704.0, 171.0, -1248.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(161, 152068, "Stone", "f_siauliai_out", -1591.0, 171.0, -1208.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(162, 152068, "Stone", "f_siauliai_out", -1514.0, 171.0, -1323.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(163, 152068, "Stone", "f_siauliai_out", -1426.0, 171.0, -1163.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(164, 152068, "Stone", "f_siauliai_out", -1229.0, 171.0, -1099.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(165, 152068, "Stone", "f_siauliai_out", -1186.0, 171.0, -975.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(166, 152068, "Stone", "f_siauliai_out", -1090.0, 171.0, -1151.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(167, 152068, "Stone", "f_siauliai_out", -1560.0, 171.0, -826.0, 0.0, "SIAULIAIOUT_STONE", "", "", -2, 20.0);
		AddNpc(202, 20168, "Healer Lady", "f_siauliai_out", -1913.0, 40.0, -1428.0, 46.0, "SIAULIAIOUT_HEALER_B", "", "", -2, 50.0);
		AddNpc(203, 20168, "Healer Lady", "f_siauliai_out", -1913.0, 40.0, -1428.0, -145.0, "SIAULIAIOUT_HEALER_C", "", "", -2, 50.0);
		AddNpc(300, 20026, "", "f_siauliai_out", 506.0, 35.0, -1622.0, -90.0, "", "SIAULIAIOUT_Q01", "", -2, 80.0);
		AddNpc(306, 45315, "Empty Wagon", "f_siauliai_out", -82.0, 156.0, -612.0, -29.0, "", "SIAULIAIOUT_CART", "", -2, 50.0);
		AddNpc(306, 45315, "Empty Wagon", "f_siauliai_out", -41.0, 157.0, -608.0, -90.0, "", "SIAULIAIOUT_CART", "", -2, 50.0);
		AddNpc(306, 45315, "Empty Wagon", "f_siauliai_out", -64.0, 161.0, -557.0, -90.0, "", "SIAULIAIOUT_CART", "", -2, 50.0);
		AddNpc(308, 20109, "Veteran Miner", "f_siauliai_out", -1758.601196, 170.045593, -813.779236, 180.0, "SIAULIAIOUT_MINER_B", "", "", -2, 20.0);
		AddNpc(309, 20109, "Veteran Miner", "f_siauliai_out", 355.0, 43.0, -1117.0, -90.0, "SIAULIAIOUT_MINER_A", "", "", -2, 20.0);
		AddNpc(311, 20026, "", "f_siauliai_out", 1900.0, 148.0, 130.0, 0.0, "", "SIAULIAIOUT_MIRTIS", "", -2, 80.0);
		AddNpc(312, 20118, "Tobias", "f_siauliai_out", -87.647362, 145.231903, -802.08905, 0.0, "SIAULIAIOUT_CHIEF_A", "", "", -2, 50.0);
		AddNpc(313, 20110, "Miners' Village Alchemist", "f_siauliai_out", 1309.118652, 147.351593, 331.725952, -86.0, "SIAULIAIOUT_ALCHE", "", "", -2, 50.0);
		AddNpc(314, 20026, "", "f_siauliai_out", 1298.0, 147.0, 307.0, 0.0, "", "SIAULIAIOUT_PREAL", "", -2, 260.0);
		AddNpc(315, 20026, "", "f_siauliai_out", 1434.0, 231.0, 535.0, 0.0, "", "SIAULIAIOUT_BOSS", "", -2, 200.0);
		AddNpc(316, 20026, "", "f_siauliai_out", -468.0, 39.0, -1514.0, 0.0, "", "SIAULIAIOUT_Q03", "", -2, 220.0);
		AddNpc(317, 47245, "Hunter", "f_siauliai_out", -945.0, 39.0, -1812.0, 0.0, "SIAULIAIOUT_HUNTER", "", "", -2, 50.0);
		AddNpc(318, 20026, "", "f_siauliai_out", -1143.0, 169.0, -1248.0, 0.0, "", "SIAULIAIOUT_Q06", "", -2, 150.0);
		AddNpc(319, 20026, "", "f_siauliai_out", 828.0, 37.0, -931.0, 0.0, "", "SIAULIAIOUT_Q11", "", -2, 150.0);
		AddNpc(320, 20026, "", "f_siauliai_out", 1377.0, 43.0, -455.0, 0.0, "", "SIAULIAIOUT_Q12", "", -2, 70.0);
		AddNpc(321, 20110, "Miners' Village Alchemist", "f_siauliai_out", -38.880001, 85.269997, -1021.809998, 0.0, "SIAULIAIOUT_ALCHE_A", "SIAULIAIOUT_ALCHE_A", "", -2, 20.0);
		AddNpc(322, 40095, "", "f_siauliai_out", -61.0, 157.0, -656.0, 0.0, "SIAULIAIOUT_BLOCK", "", "", -2, 20.0);
		AddNpc(329, 20026, "", "f_siauliai_out", -1531.77002, 42.830002, -1751.319946, 0.0, "", "SOUT_SUDD", "", -2, 200.0);
		AddNpc(342, 20025, "", "f_siauliai_out", -142.934555, 160.270004, -221.02887, 0.0, "JOB_KRIWI1_OUT", "", "", -2, 1.0);
		AddNpc(6001, 147507, "Npc Hunting Grounds Entrance", "f_siauliai_out", 57.400002, 276.100006, 336.700012, 0.0, "PVP_MINE_TEAM_NPC", "", "", -2, 1.0);
		AddNpc(10001, 20041, "", "f_siauliai_out", 1911.0, 140.0, 75.0, 0.0, "", "JOB_HUNTER2_1_TRIGGER", "", -2, 100.0);
		AddNpc(10003, 20041, "", "f_siauliai_out", 57.0, 153.0, -133.0, 0.0, "", "JOB_HUNTER2_3_TRIGGER", "", -2, 300.0);
		AddNpc(10004, 40070, "Bulletin Board", "f_siauliai_out", -142.0, 153.0, -435.0, 0.0, "F_SIAULIA_OUT_BOARD01", "", "", -2, 30.0);
		AddNpc(10005, 20041, "", "f_siauliai_out", 49.0, 85.0, -1038.0, 0.0, "", "JOB_PRIEST2_1_TRIGGER", "", -2, 100.0);
		AddNpc(10007, 20114, "Marta", "f_siauliai_out", -54.0, 85.0, -1064.0, 0.0, "F_SIAU_OUT_NPC01", "", "", -2, 100.0);
		AddNpc(10008, 20150, "Veteran Miner 2", "f_siauliai_out", 36.0, 85.0, -968.0, 0.0, "F_SIAU_OUT_NPC02", "", "", -2, 100.0);
		AddNpc(10009, 147473, "Mira", "f_siauliai_out", 66.0, 88.0, -1083.0, 0.0, "F_SIAU_OUT_NPC03", "", "", -2, 30.0);
		AddNpc(10014, 40070, "Bulletin Board", "f_siauliai_out", 129.0, 153.0, -18.0, 270.0, "F_SIAULIAI_OUT_BOARD02", "", "", -2, 100.0);
		AddNpc(10016, 155072, "Psychokino Submaster", "f_siauliai_out", 554.107788, 42.792099, -879.425659, -45.0, "JOB_PSYCHOKINESIST2_1_NPC", "", "", -2, 40.0);
		AddNpc(10017, 155073, "Linker Submaster", "f_siauliai_out", 312.0, 88.0, -1010.0, -130.0, "JOB_LINKER2_1_NPC", "", "", -2, 40.0);
		AddNpc(10020, 20026, "", "f_siauliai_out", 1463.910034, 213.649994, 478.929993, 0.0, "", "JOB_PSYCHOKINESIST4_1_TRIGGER", "", -2, 200.0);
		AddNpc(10021, 20026, "", "f_siauliai_out", -2108.23999, 42.830002, -1829.400024, 31.0, "", "JOB_SPYLIAL5_1_TRIGGER", "", -2, 300.0);
		AddNpc(10026, 147392, "Treasure Box 1", "f_siauliai_out", 1651.869995, 147.350006, 427.339996, 0.0, "TREASUREBOX_BUBE", "", "", -2, 40.0);
		AddNpc(10031, 40110, "Statue Of Goddess Zemyna", "f_siauliai_out", -2194.0, 40.0, -2055.0, -6.4, "F_SIAULIAI_OUT_EV_55_001", "F_SIAULIAI_OUT_EV_55_001", "F_SIAULIAI_OUT_EV_55_001", -2, 150.0);
		AddNpc(10032, 20026, "", "f_siauliai_out", 83.149284, 88.360901, -1082.023193, 0.0, "", "JOB_CLERIC2_2_TRIGGER", "", -2, 200.0);
		AddNpc(10033, 152000, "Ordinary Husband", "f_siauliai_out", -2242.070068, 42.830002, -1971.589966, -18.0, "SOUT_REFUGEE01", "", "", -2, 40.0);
		AddNpc(10034, 152001, "Ordinary Wife", "f_siauliai_out", -2266.51001, 42.830002, -1973.569946, -108.0, "SOUT_REFUGEE02", "", "", -2, 40.0);
		AddNpc(10036, 152000, "Ordinary Husband", "f_siauliai_out", -1958.963379, 42.826401, -1449.023315, -18.0, "SOUT_REFUGEE01_1", "", "", -2, 40.0);
		AddNpc(10037, 152001, "Ordinary Wife", "f_siauliai_out", -1935.06189, 42.826401, -1467.271362, 45.0, "SOUT_REFUGEE02_1", "", "", -2, 40.0);
		AddNpc(10044, 40070, "Bulletin Board", "f_siauliai_out", -58.0, 150.0, -133.0, -45.0, "F_SIAULIAI_OUT_BOARD03", "", "", -2, 100.0);
		AddNpc(10045, 20109, "Veteran Miner", "f_siauliai_out", -1758.601196, 170.045593, -813.779236, -75.0, "SIAULIAIOUT_MINER_C", "", "", -2, 40.0);
		AddNpc(10046, 147493, "Chemist", "f_siauliai_out", -47.847763, 85.268799, -1212.506348, 0.0, "SOUT_PHARMACY", "", "", -2, 40.0);
		AddNpc(10048, 20016, "Western Woods Scout", "f_siauliai_out", 90.956902, 50.216507, -1225.092041, 0.0, "SIAULIAIOUT_SOLDIRE_SQ31", "", "", -2, 40.0);
		AddNpc(10049, 20019, "Western Woods Scout", "f_siauliai_out", 429.014557, 42.792099, -1201.717896, 0.0, "SIAULIAIOUT_SOLDIRE_SQ32", "", "", -2, 40.0);
		AddNpc(10050, 20045, "", "f_siauliai_out", -60.966164, 157.296173, -605.291138, 0.0, "", "SOUT_Q_16_WALL", "", -2, 10.0);
		AddNpc(10053, 47252, "Royal Mausoleum Tombstone02", "f_siauliai_out", 323.661285, 150.397949, -190.628891, -63.0, "SIAU_HUAN_MNT", "", "", -2, 5.0);
		AddNpc(10054, 147392, "Treasure Box 1", "f_siauliai_out", 1224.349976, 198.020004, 279.950012, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(10055, 20026, "", "f_siauliai_out", -73.104187, 150.795868, -209.059128, 0.0, "", "JOB_QUARRELSHOOTER1_TRIGGER", "", -2, 75.0);
		AddNpc(10056, 40095, "", "f_siauliai_out", 1534.596436, 146.851593, 221.916611, 0.0, "", "EXPLORER_MISLE3", "", -2, 20.0);
	}
}
