// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using Melia.Zone.Scripting;
using static Melia.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_2 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(2, 20125, "Mid Commander (Male 2)", "f_siauliai_2", 167.0, 151.0, 697.0, -90.0, "SIAUL_EAST_MANAGER", "", "", -2, 35.0);
		AddNpc(30, 20014, "Head Of Guard Troop", "f_siauliai_2", -1290.0, 130.0, 928.0, -90.0, "SIAUL_EAST_SUPPLY_MANAGER2", "", "", -2, 35.0);
		AddNpc(38, 20041, "", "f_siauliai_2", 164.0, 130.0, 440.0, -90.0, "", "SIAUL_EAST_CAMP4", "", -2, 50.0);
		AddNpc(38, 20041, "", "f_siauliai_2", -46.0, 151.0, 818.0, 0.0, "", "SIAUL_EAST_CAMP4", "", -2, 50.0);
		AddNpc(39, 20041, "", "f_siauliai_2", 206.0, 130.0, 428.0, -90.0, "", "SIAUL_EAST_RECLAIM1", "", -2, 200.0);
		AddNpc(40, 20041, "", "f_siauliai_2", 487.257996, 130.022705, -309.289703, -90.0, "", "SIAUL_EAST_RECLAIM3", "", -2, 250.0);
		AddNpc(40, 20041, "", "f_siauliai_2", 515.283325, 130.022705, -528.239685, -90.0, "", "SIAUL_EAST_RECLAIM3", "", -2, 250.0);
		AddNpc(41, 20016, "Western Woods Scout", "f_siauliai_2", 660.709595, 130.022705, -453.273926, -90.0, "SIAUL_EAST_SUPPLY_MANAGER", "", "", -2, 35.0);
		AddNpc(42, 20016, "Western Woods Scout", "f_siauliai_2", 615.0, 130.0, -196.0, -90.0, "SIAUL_EAST_SOLDIER4", "", "", -2, 50.0);
		AddNpc(43, 20011, "Supply Soldier", "f_siauliai_2", 741.0, 130.0, 411.0, -90.0, "SIAUL_EAST_SOLDIER5", "", "", -2, 50.0);
		AddNpc(45, 20013, "Supply Officer", "f_siauliai_2", 357.0, 130.0, 593.0, -90.0, "SIAUL_EAST_SOLDIER6", "", "", -2, 50.0);
		AddNpc(46, 20015, "View", "f_siauliai_2", 210.0, 130.0, 260.0, -90.0, "SIAUL_EAST_SOLDIER7", "", "", -2, 50.0);
		AddNpc(47, 20041, "", "f_siauliai_2", 462.0, 130.0, -882.0, -90.0, "", "SIAUL_EAST_RECLAIM7", "", -2, 40.0);
		AddNpc(48, 20041, "", "f_siauliai_2", -2124.0, 130.0, 1122.0, -90.0, "", "SIAUL_EAST_REQUEST2", "", -2, 150.0);
		AddNpc(48, 20041, "", "f_siauliai_2", -2241.0, 130.0, 1047.0, -90.0, "", "SIAUL_EAST_REQUEST2", "", -2, 150.0);
		AddNpc(49, 20041, "", "f_siauliai_2", 1165.00415, 138.7939, 218.175323, -90.0, "", "SIAUL_EAST_REQUEST3", "", -2, 60.0);
		AddNpc(51, 20041, "", "f_siauliai_2", 1886.657837, 185.094894, -476.827393, -90.0, "", "SIAUL_EAST_REQUEST6", "", -2, 100.0);
		AddNpc(54, 20041, "", "f_siauliai_2", 1650.0, 186.0, 931.0, -90.0, "", "SIAUL_EAST_BUBE", "", -2, 40.0);
		AddNpc(61, 46212, "Box", "f_siauliai_2", 301.0, 130.0, -569.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(62, 46212, "Box", "f_siauliai_2", 289.0, 130.0, -758.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(63, 46212, "Box", "f_siauliai_2", 176.0, 130.0, -492.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(64, 46212, "Box", "f_siauliai_2", 125.0, 130.0, -247.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(65, 46212, "Box", "f_siauliai_2", -158.0, 130.0, -876.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(66, 46212, "Box", "f_siauliai_2", -270.0, 130.0, -581.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(67, 46212, "Box", "f_siauliai_2", -223.0, 130.0, -452.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(68, 46212, "Box", "f_siauliai_2", 952.0, 130.0, -742.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(69, 46212, "Box", "f_siauliai_2", 728.0, 130.0, -789.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(70, 46212, "Box", "f_siauliai_2", 309.89563, 130.022705, -335.39978, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(71, 46212, "Box", "f_siauliai_2", 600.0, 130.0, -19.0, 87.0, "ACT2_DISS1_BOX", "", "", -2, 40.0);
		AddNpc(704, 20041, "", "f_siauliai_2", -1143.0, 129.0, 884.0, 0.0, "", "SIAUL_EAST_REQUEST1_S1_TRIGGER", "", -2, 200.0);
		AddNpc(10001, 147434, "Sapper Master", "f_siauliai_2", 440.719604, 162.458298, 1204.536743, -90.0, "JOB_SAPPER2_1_NPC", "", "", -2, 30.0);
		AddNpc(10002, 57231, "Hunter Master", "f_siauliai_2", 379.997772, 162.458298, 1196.954956, -90.0, "JOB_HUNTER2_1_NPC", "", "", -2, 30.0);
		AddNpc(10005, 40070, "Bulletin Board", "f_siauliai_2", -969.0, 130.0, 63.0, -39.0, "F_SIAULIA_2_BOARD01", "", "", -2, 30.0);
		AddNpc(10009, 20041, "", "f_siauliai_2", 1145.0, 130.0, -725.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 10.0);
		AddNpc(10010, 20041, "", "f_siauliai_2", -2005.0, 130.0, 1639.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 40.0);
		AddNpc(10015, 57237, "Barbarian Master", "f_siauliai_2", 316.862244, 162.458298, 1178.065186, -90.0, "JOB_BARBARIAN2_NPC", "", "", -2, 30.0);
		AddNpc(10017, 20026, "", "f_siauliai_2", -1247.508545, 243.522202, -1485.487793, 0.0, "", "JOB_BOCOR4_4_TRIGGER", "", -2, 150.0);
		AddNpc(10018, 20026, "", "f_siauliai_2", 564.03656, 130.022705, 278.162659, 0.0, "", "JOB_PYROMANCER4_1_TRIGGER", "", -2, 400.0);
		AddNpc(10019, 20026, "", "f_siauliai_2", 2017.164063, 185.094894, -395.472839, 0.0, "", "JOB_LINKER4_1_TRIGGER", "", -2, 200.0);
		AddNpc(10021, 20026, "", "f_siauliai_2", -2269.650879, 130.022705, 1192.536987, 0.0, "", "JOB_WIPYCRY5_1_TRIGGER", "", -2, 200.0);
		AddNpc(10023, 40030, "Treasure Chest", "f_siauliai_2", 49.240002, 130.119995, -963.25, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(10037, 153056, "Empty Wagon Collusion Box Present", "f_siauliai_2", 478.744385, 130.022705, -511.839966, 0.0, "", "", "", -2, 40.0);
		AddNpc(10037, 153056, "Empty Wagon Collusion Box Present", "f_siauliai_2", 487.403564, 130.022705, -468.582947, -42.0, "", "", "", -2, 40.0);
		AddNpc(10037, 153056, "Empty Wagon Collusion Box Present", "f_siauliai_2", 578.240662, 130.022705, -448.171906, 53.0, "", "", "", -2, 40.0);
		AddNpc(10038, 20026, "", "f_siauliai_2", -269.269135, 130.022705, 1009.521973, 0.0, "", "SIAULIA_2_JOB_SPARRING_TRIGGER", "", -2, 200.0);
		AddNpc(10039, 147392, "Treasure Box 1", "f_siauliai_2", -2235.570068, 130.119995, 690.809998, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(10042, 46212, "Box", "f_siauliai_2", 223.619995, 130.020004, -455.299988, 100.0, "LOWLV_BOASTER_SQ_10_BOX", "", "", -2, 40.0);
		AddNpc(10042, 46212, "Box", "f_siauliai_2", 279.230011, 130.020004, -214.070007, 39.0, "LOWLV_BOASTER_SQ_10_BOX", "", "", -2, 40.0);
		AddNpc(10042, 46212, "Box", "f_siauliai_2", 321.410004, 130.020004, -702.450012, 99.0, "LOWLV_BOASTER_SQ_10_BOX", "", "", -2, 40.0);
		AddNpc(10042, 46212, "Box", "f_siauliai_2", 440.450012, 130.020004, -343.799988, 43.0, "LOWLV_BOASTER_SQ_10_BOX", "", "", -2, 40.0);
		AddNpc(10042, 46212, "Box", "f_siauliai_2", 486.079987, 130.020004, -162.389999, 80.0, "LOWLV_BOASTER_SQ_10_BOX", "", "", -2, 40.0);
		AddNpc(10042, 46212, "Box", "f_siauliai_2", 491.630005, 130.050003, -579.609985, 83.0, "LOWLV_BOASTER_SQ_10_BOX", "", "", -2, 40.0);
		AddNpc(10042, 46212, "Box", "f_siauliai_2", 78.190002, 130.020004, -366.910004, 105.0, "LOWLV_BOASTER_SQ_10_BOX", "", "", -2, 40.0);
		AddNpc(10043, 40095, "", "f_siauliai_2", -760.905518, 243.522202, -712.129944, 0.0, "", "EXPLORER_MISLE2", "", -2, 20.0);
		AddNpc(10044, 20026, "", "f_siauliai_2", 2068.242676, 185.094894, -508.521973, 0.0, "", "CHAR220_MSETP2_1_2_GEN_INIT", "", -2, 40.0);
	}
}
