// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using Melia.Zone.Scripting;
using static Melia.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_16 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(2, 151082, "Orsha Soldier Male5 2", "f_siauliai_16", -2334.041504, 115.9076, -1400.89502, -90.0, "SIAULIAI16_BOWEIN", "", "", -2, 1.0);
		AddNpc(3, 151083, "Orsha Soldier Male6 1", "f_siauliai_16", -1540.714966, 65.4132, -1274.198853, -83.0, "SIAULIAI16_BROPHEN", "", "", -2, 1.0);
		AddNpc(4, 20061, "Orsha Soldier Female1", "f_siauliai_16", -911.111633, 25.350403, -393.229218, -76.0, "SIAULIAI16_RHEILAR", "", "", -2, 1.0);
		AddNpc(5, 151096, "Orsha Soldier Male12 2", "f_siauliai_16", 271.140686, 25.350403, 287.192627, -89.0, "SIAULIAI16_ROMANAS", "", "", -2, 1.0);
		AddNpc(6, 151090, "Orsha Soldier Male9 2", "f_siauliai_16", 387.0, 25.350403, 323.0, -90.0, "SIAULIAI16_DALLANAS", "", "", -2, 1.0);
		AddNpc(7, 151091, "Orsha Soldier Male10 1", "f_siauliai_16", 199.399368, 25.350399, 147.886841, 1.0, "SIAULIAI16_IHBANAYUS", "", "", -2, 1.0);
		AddNpc(8, 151080, "Orsha Soldier Female 4", "f_siauliai_16", 152.932098, 25.350403, 307.766022, -50.0, "SIAULIAI16_IZNA", "", "", -2, 1.0);
		AddNpc(10, 40110, "Statue Of Goddess Zemyna", "f_siauliai_16", 13.888562, 79.773598, 1277.24939, -30.0, "SIAU16_SQ_06_EV_NPC", "", "", -2, 1.0);
		AddNpc(13, 151086, "Orsha Soldier Male7 2", "f_siauliai_16", 2025.056519, 25.350403, 331.472656, -74.0, "SIAULIAI16_LUTAS", "", "", -2, 40.0);
		AddNpc(14, 151081, "Orsha Soldier Male5 1", "f_siauliai_16", 2012.560791, 25.350403, 298.365997, 67.0, "SIAU16_MQ_06_NPC_1", "", "", -2, 1.0);
		AddNpc(15, 151092, "Orsha Soldier Male10 2", "f_siauliai_16", 2002.461548, 25.350403, 273.597382, 66.0, "SIAU16_MQ_06_NPC_2", "", "", -2, 1.0);
		AddNpc(16, 20062, "Orsha Soldier Female2", "f_siauliai_16", 1990.848389, 25.350403, 246.969742, 47.0, "SIAU16_MQ_06_NPC_3", "", "", -2, 1.0);
		AddNpc(300, 155064, "Highlander Submaster", "f_siauliai_16", 882.837463, 25.350403, 221.612213, -102.0, "JOB_2_HIGHLANDER_NPC", "SIAULIAI16_HQ1_SSN_CREATE", "", -2, 100.0);
		AddNpc(302, 20064, "Orsha Soldier Male2", "f_siauliai_16", -634.236206, 74.851799, 676.373352, -78.0, "JOB_2_CLERIC3_PATIENT", "", "", -2, 40.0);
		AddNpc(302, 20064, "Orsha Soldier Male2", "f_siauliai_16", -346.216705, 74.851799, 1152.96228, -127.0, "JOB_2_CLERIC3_PATIENT", "", "", -2, 40.0);
		AddNpc(302, 20064, "Orsha Soldier Male2", "f_siauliai_16", -617.854797, 74.851799, 1569.731812, 91.0, "JOB_2_CLERIC3_PATIENT", "", "", -2, 40.0);
		AddNpc(303, 151080, "Orsha Soldier Female 4", "f_siauliai_16", -203.145065, 74.851799, 563.392212, -2.0, "JOB_2_CLERIC3_PATIENT", "", "", -2, 40.0);
		AddNpc(303, 151080, "Orsha Soldier Female 4", "f_siauliai_16", -1116.566528, 74.851799, 1047.924805, -48.0, "JOB_2_CLERIC3_PATIENT", "", "", -2, 40.0);
		AddNpc(303, 151080, "Orsha Soldier Female 4", "f_siauliai_16", -440.660522, 74.851799, 1683.155396, 162.0, "JOB_2_CLERIC3_PATIENT", "", "", -2, 40.0);
		AddNpc(304, 155118, "Orsha Soldier Male14 1", "f_siauliai_16", -697.203552, 74.851799, 1139.38147, -98.0, "JOB_2_CLERIC3_PATIENT", "", "", -2, 40.0);
		AddNpc(304, 155118, "Orsha Soldier Male14 1", "f_siauliai_16", -860.374695, 74.911064, 1644.570923, 0.0, "JOB_2_CLERIC3_PATIENT", "", "", -2, 40.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -1204.286743, 74.851799, 1365.780762, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -1203.485107, 74.851799, 1192.551147, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -1059.281738, 74.851799, 1024.21167, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -859.516724, 74.851799, 889.16864, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -1133.684692, 74.851799, 1853.054443, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -929.16217, 74.851799, 1907.166504, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -834.442261, 74.851799, 1569.936035, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -1137.766968, 74.851799, 1655.688232, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -485.766815, 74.851799, 1805.558838, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -619.22644, 74.851799, 1553.016479, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -694.365601, 74.851799, 1287.05481, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -299.288055, 74.851799, 1027.971436, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -866.848083, 74.851799, 1209.555176, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -343.011353, 74.851799, 1183.322876, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(306, 154060, "Bonfireq1", "f_siauliai_16", -676.333069, 74.851799, 898.001343, 0.0, "SIAU16_SQ_03_NPC", "", "", -2, 1.0);
		AddNpc(307, 47223, "Firewood", "f_siauliai_16", -482.0, 75.0, 1531.0, -148.0, "SIAU16_SQ_04_NPC", "", "", -2, 1.0);
		AddNpc(308, 153041, "Sack Of Crops", "f_siauliai_16", 1312.931763, 25.350403, -1056.440674, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(308, 153041, "Sack Of Crops", "f_siauliai_16", 1368.174805, 25.350403, -1159.317505, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(308, 153041, "Sack Of Crops", "f_siauliai_16", 1472.748047, 25.350403, -934.278198, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(308, 153041, "Sack Of Crops", "f_siauliai_16", 1378.477173, 25.350403, -824.027222, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(308, 153041, "Sack Of Crops", "f_siauliai_16", 1737.606323, 25.350403, -560.962219, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(308, 153041, "Sack Of Crops", "f_siauliai_16", 1726.476196, 25.350403, -679.953003, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(308, 153041, "Sack Of Crops", "f_siauliai_16", 1517.048462, 25.350403, -872.685059, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(309, 47161, "Lost Stuff Of Vendor 2", "f_siauliai_16", 1603.94873, 25.350403, -601.484131, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(309, 47161, "Lost Stuff Of Vendor 2", "f_siauliai_16", 1506.282349, 25.350403, -787.907837, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(309, 47161, "Lost Stuff Of Vendor 2", "f_siauliai_16", 1308.947021, 25.350403, -741.8078, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(309, 47161, "Lost Stuff Of Vendor 2", "f_siauliai_16", 1641.760376, 25.350399, -771.625854, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(309, 47161, "Lost Stuff Of Vendor 2", "f_siauliai_16", 1266.900879, 25.350403, -892.610107, 0.0, "SIAU16_SQ_05_NPC", "", "", -2, 1.0);
		AddNpc(310, 151087, "Orsha Soldier Male8 1", "f_siauliai_16", 36.117081, 79.773598, 989.140076, 0.0, "SIAU16_SQ_08_NPC_1", "", "", -2, 40.0);
		AddNpc(310, 151087, "Orsha Soldier Male8 1", "f_siauliai_16", 905.568665, 79.773598, 1464.534668, 175.0, "SIAU16_SQ_08_NPC_1", "", "", -2, 40.0);
		AddNpc(310, 151087, "Orsha Soldier Male8 1", "f_siauliai_16", 126.504158, 102.620201, 1763.647949, 0.0, "SIAU16_SQ_08_NPC_1", "", "", -2, 40.0);
		AddNpc(311, 151094, "Orsha Soldier Male11 2", "f_siauliai_16", 262.294617, 79.773598, 857.933838, -163.0, "SIAU16_SQ_08_NPC_2", "", "", -2, 40.0);
		AddNpc(311, 151094, "Orsha Soldier Male11 2", "f_siauliai_16", 432.976837, 94.081909, 1719.86145, -95.0, "SIAU16_SQ_08_NPC_2", "", "", -2, 40.0);
		AddNpc(311, 151094, "Orsha Soldier Male11 2", "f_siauliai_16", 997.823669, 79.773598, 1813.569458, -108.0, "SIAU16_SQ_08_NPC_2", "", "", -2, 40.0);
		AddNpc(312, 151097, "Orsha Soldier Male13 1", "f_siauliai_16", 777.667419, 79.773598, 1946.410767, -79.0, "SIAU16_SQ_08_NPC_3", "", "", -2, 40.0);
		AddNpc(312, 151097, "Orsha Soldier Male13 1", "f_siauliai_16", 43.10017, 79.773598, 1274.85437, 114.0, "SIAU16_SQ_08_NPC_3", "", "", -2, 40.0);
		AddNpc(312, 151097, "Orsha Soldier Male13 1", "f_siauliai_16", 896.996094, 79.773598, 1032.209595, 147.0, "SIAU16_SQ_08_NPC_3", "", "", -2, 40.0);
		AddNpc(323, 147311, "Book", "f_siauliai_16", 650.0, 25.0, 314.0, 0.0, "ORSHA_BOOK_DIARY01", "", "", -2, 40.0);
		AddNpc(324, 147392, "Treasure Box 1", "f_siauliai_16", -2294.0, 116.0, -1886.0, 90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(325, 147392, "Treasure Box 1", "f_siauliai_16", -594.0, 25.0, -1993.0, 45.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(326, 147392, "Treasure Box 1", "f_siauliai_16", 1750.0, 26.0, -564.0, 270.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(327, 153172, "Taoist Master", "f_siauliai_16", 710.542725, 25.350401, -461.906219, 0.0, "DAOSHI_MASTER", "", "", -2, 40.0);
		AddNpc(328, 20063, "Orsha Soldier Male1", "f_siauliai_16", 109.401047, 25.350403, -416.241913, 0.0, "CHAR119_MSTEP3_3_1_NPC", "", "", -2, 40.0);
		AddNpc(329, 40095, "", "f_siauliai_16", -1192.460693, 74.851799, 1513.11084, 0.0, "", "EXPLORER_MISLE11", "", -2, 20.0);
	}
}
