// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using Melia.Zone.Scripting;
using static Melia.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_west : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 20063, "Orsha Soldier Male1", "f_siauliai_west", -1121.0, 260.0, -528.0, -99.0, "SIALUL_WEST_DRASIUS", "", "", -2, 150.0);
		AddNpc(3, 20016, "Search Scout", "f_siauliai_west", -1488.0, 260.0, -138.0, -90.0, "SIAUL_WEST_NAGLIS2", "SIAUL_WEST_NAGLIS2", "SIAUL_WEST_NAGLIS2", -2, 30.0);
		AddNpc(5, 20041, "", "f_siauliai_west", -2005.0, 260.0, 102.0, 0.0, "", "SIALUL_WEST_ONION_BIG_TRIGGER", "", -2, 40.0);
		AddNpc(5, 20041, "", "f_siauliai_west", -1765.0, 260.0, 102.0, 0.0, "", "SIALUL_WEST_ONION_BIG_TRIGGER", "", -2, 40.0);
		AddNpc(5, 20041, "", "f_siauliai_west", -1845.0, 260.0, 102.0, 0.0, "", "SIALUL_WEST_ONION_BIG_TRIGGER", "", -2, 40.0);
		AddNpc(5, 20041, "", "f_siauliai_west", -1925.0, 260.0, 102.0, 0.0, "", "SIALUL_WEST_ONION_BIG_TRIGGER", "", -2, 40.0);
		AddNpc(7, 20107, "Mid Commander (Female)", "f_siauliai_west", -576.0, 260.0, -719.0, 164.880005, "SIAUL_WEST_CAMP_MANAGER", "", "", -2, 70.0);
		AddNpc(8, 20016, "Western Woods Scout", "f_siauliai_west", -652.0, 260.0, -953.0, -90.0, "SIAU_FRON_NPC_01", "", "", -2, 80.0);
		AddNpc(9, 20117, "Armand", "f_siauliai_west", 326.508606, 210.211899, -346.852936, -90.0, "SIAUL_WEST_LAIMONAS", "", "", -2, 0.0);
		AddNpc(11, 20114, "Marta", "f_siauliai_west", -624.0, 260.0, -385.0, -83.93, "SIAUL_WEST_RESIDENT1", "", "", -2, 0.0);
		AddNpc(12, 20041, "", "f_siauliai_west", 773.0, 258.0, -125.0, 0.0, "", "SIAUL_WEST_LAIMONAS1_TRIGGER", "SIAUL_WEST_LAIMONAS1_TRIGGER", -2, 120.0);
		AddNpc(14, 20041, "", "f_siauliai_west", 980.0, 285.0, 559.0, 0.0, "", "SIAUL_WEST_LAIMONAS2_TRIGGER", "", -2, 60.0);
		AddNpc(21, 20041, "", "f_siauliai_west", -403.0, 322.0, 363.0, 0.0, "", "SIAUL_WEST_HANAMING_TRIGGER", "", -2, 50.0);
		AddNpc(27, 20019, "Western Woods Scout", "f_siauliai_west", 1626.0, 210.0, -798.0, 180.0, "SIAUL_ST1_ST2", "", "", -2, 0.0);
		AddNpc(31, 47239, "Sculptor", "f_siauliai_west", -751.015503, 260.825409, -362.257416, -90.0, "JOB_DIEVDIRBYS2_NPC", "", "", -2, 40.0);
		AddNpc(32, 47248, "Cat", "f_siauliai_west", -778.916138, 260.825409, -353.646851, -90.0, "JOB_DIEVDIRBYS3_3_NPC", "", "", -2, 40.0);
		AddNpc(49, 20026, "", "f_siauliai_west", -443.0, 322.0, 120.0, 0.0, "", "SIAUL_WEST_ADD_SUB_01", "", -2, 180.0);
		AddNpc(50, 20026, "", "f_siauliai_west", 1565.729248, 285.045807, 327.552399, 0.0, "", "SIAUL_WEST_LAIMONAS3_2_TRIGGER", "", -2, 70.0);
		AddNpc(55, 20026, "", "f_siauliai_west", -560.0, 260.0, -780.0, 0.0, "", "SIAUL_WEST_MEET_TITAS_AUTO", "", -2, 200.0);
		AddNpc(1002, 40080, "Warning", "f_siauliai_west", -1566.0, 260.0, -1096.0, -82.720001, "SIAUL1_BOARD2", "", "", -2, 10.0);
		AddNpc(1003, 40080, "Warning", "f_siauliai_west", -1692.0, 260.0, -150.0, -86.099998, "SIAUL1_BOARD3", "", "", -2, 10.0);
		AddNpc(1004, 40070, "Bulletin Board", "f_siauliai_west", 487.0, 209.0, -139.0, -50.709999, "SIAUL1_BOARD4", "", "", -2, 10.0);
		AddNpc(1005, 40080, "Warning", "f_siauliai_west", -572.0, 322.0, 449.0, 92.120003, "SIAUL1_BOARD5", "", "", -2, 10.0);
		AddNpc(1006, 40070, "Bulletin Board", "f_siauliai_west", -695.0, 322.0, 840.0, -64.089996, "SIAUL1_BOARD6", "", "", -2, 10.0);
		AddNpc(1007, 40070, "Bulletin Board", "f_siauliai_west", -547.0, 260.0, -453.0, -93.269997, "SIAUL1_BOARD7", "", "", -2, 10.0);
		AddNpc(2002, 20016, "Western Woods Scout", "f_siauliai_west", -663.0, 322.0, 503.0, 0.0, "SIAUL_WEST_SOL3", "", "", -2, 0.0);
		AddNpc(2007, 20041, "", "f_siauliai_west", -550.0, 359.0, 1370.0, -90.0, "", "SIAUL_WEST_BOSS_GOLEM_TRIGGER", "", -2, 400.0);
		AddNpc(2011, 40070, "Bulletin Board", "f_siauliai_west", -1822.0, 260.0, -925.0, 315.0, "SIAUL1_BOARDCRYSTAL", "", "", -2, 30.0);
		AddNpc(2012, 20041, "", "f_siauliai_west", 175.0, 322.0, 384.0, 0.0, "", "JOB_SAPPER2_1_TRIGGER", "", -2, 100.0);
		AddNpc(2013, 155065, "Hoplite Submaster", "f_siauliai_west", -331.0, 260.0, -400.0, -90.0, "JOB_HOPLITE2_NPC", "", "", -2, 40.0);
		AddNpc(2014, 20026, "", "f_siauliai_west", 1505.410034, 210.210007, -778.630005, 0.0, "", "JOB_KRIVI4_2_TRACK", "", -2, 200.0);
		AddNpc(2015, 20026, "", "f_siauliai_west", -595.969971, 359.519989, 1356.170044, 0.0, "", "JOB_WIZARD4_1_TRIGGER", "", -2, 250.0);
		AddNpc(2016, 20026, "", "f_siauliai_west", 1697.449951, 285.049988, 387.609985, 0.0, "", "JOB_CRYOMANCER4_1_TRIGGER", "", -2, 100.0);
		AddNpc(2018, 40070, "Bulletin Board", "f_siauliai_west", 1615.969971, 210.210007, -713.26001, -97.0, "SIAUL_WEST_HQ01_INFO01", "", "", -2, 40.0);
		AddNpc(2019, 40070, "Bulletin Board", "f_siauliai_west", -558.599976, 260.829987, -1021.280029, 179.0, "SIAUL_WEST_HQ01_INFO02", "", "", -2, 40.0);
		AddNpc(2020, 40070, "Bulletin Board", "f_siauliai_west", -1277.390015, 260.829987, -614.179993, 0.0, "SIAUL_WEST_HQ01_INFO03", "", "", -2, 40.0);
		AddNpc(2021, 147416, "Sentinel Woman 3", "f_siauliai_west", 1553.76001, 210.210007, -695.25, 0.0, "TUTO_SKIP_NPC", "", "", -2, 40.0);
		AddNpc(2025, 20026, "", "f_siauliai_west", 1428.380005, 210.210007, -922.820007, 0.0, "", "SIAUL_WEST_ROCK", "", -2, 200.0);
		AddNpc(2026, 20026, "", "f_siauliai_west", 1705.189941, 285.049988, 390.190002, 0.0, "", "SIAUL_WEST_LAIMONAS3_TRIGGER", "", -2, 60.0);
		AddNpc(2027, 147392, "Treasure Box 1", "f_siauliai_west", 1564.0, 210.0, -370.0, 180.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(2029, 40110, "Statue Of Goddess Zemyna", "f_siauliai_west", 1687.0, 285.049988, 366.0, -70.0, "F_SIAULIAI_WEST_EV_55_001", "F_SIAULIAI_WEST_EV_55_001", "F_SIAULIAI_WEST_EV_55_001", -2, 150.0);
		AddNpc(2032, 147392, "Treasure Box 1", "f_siauliai_west", -580.0, 260.0, -1417.0, 90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(2034, 147392, "Treasure Box 1", "f_siauliai_west", -2004.069946, 260.929993, -940.169983, -90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(2035, 147393, "Treasure Box 3", "f_siauliai_west", 185.809998, 210.309998, -856.900024, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(2036, 147392, "Treasure Box 1", "f_siauliai_west", 1346.050049, 210.309998, -1087.23999, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(2037, 147469, "No Shadow Npc", "f_siauliai_west", 3221.665771, 423.386536, 865.994568, 0.0, "RUNECASTER_SIAULIAI_WEST_STONE", "", "", -2, 40.0);
		AddNpc(2039, 40095, "", "f_siauliai_west", -2067.65332, 260.825409, -1273.606201, 0.0, "", "EXPLORER_MISLE1", "", -2, 20.0);
	}
}
